config/routes.rb
Rails.application.routes.draw do
  resources :foods
  get 'static_pages/about'
  get 'static_pages/User'
  get 'static_pages/Proposal'
  root 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food, :detail, :calories, :fat, :cholesterol, :sodium, :carbohydrate, :protein, :vitamin, :bitamin, :Calcium, :iron)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/foods/_form.html.haml
= form_for @food do |f|
  - if @food.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      %ul
        - @food.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :food
    = f.text_field :food
  .field
    = f.label :detail
    = f.text_area :detail
  .field
    = f.label :calories
    = f.text_field :calories
  .field
    = f.label :fat
    = f.text_field :fat
  .field
    = f.label :cholesterol
    = f.text_field :cholesterol
  .field
    = f.label :sodium
    = f.text_field :sodium
  .field
    = f.label :carbohydrate
    = f.text_field :carbohydrate
  .field
    = f.label :protein
    = f.text_field :protein
  .field
    = f.label :vitamin
    = f.text_field :vitamin
  .field
    = f.label :bitamin
    = f.text_field :bitamin
  .field
    = f.label :Calcium
    = f.text_field :Calcium
  .field
    = f.label :iron
    = f.text_field :iron
  .actions
    = f.submit 'Save'

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/index.html.haml
%h1 Listing foods

%table
  %thead
    %tr
      %th Food
      %th Detail
      %th Calories(g)
      %th Fat(g)
      %th Cholesterol(mg)
      %th Sodium(mg)
      %th Carbohydrate(g)
      %th Protein(g)
      %th Vitamin(%)
      %th Bitamin(%)
      %th Calcium(%)
      %th Iron(%)
      %th
      %th
      %th

  %tbody
    - @foods.each do |food|
      %tr
        %td= food.food
        %td= food.detail
        %td= food.calories
        %td= food.fat
        %td= food.cholesterol
        %td= food.sodium
        %td= food.carbohydrate
        %td= food.protein
        %td= food.vitamin
        %td= food.bitamin
        %td= food.Calcium
        %td= food.iron
        %td= link_to 'Show', food
        %td= link_to 'Edit', edit_food_path(food)
        %td= link_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Add food', new_food_path

app/views/foods/new.html.haml
%h1 Add food

= render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.haml
%p#notice= notice

%p
  %b Food:
  = @food.food
%p
  %b Detail:
  = @food.detail
%p
  %b Calories:
  = @food.calories
%p
  %b Fat:
  = @food.fat
%p
  %b Cholesterol:
  = @food.cholesterol
%p
  %b Sodium:
  = @food.sodium
%p
  %b Carbohydrate:
  = @food.carbohydrate
%p
  %b Protein:
  = @food.protein
%p
  %b Vitamin:
  = @food.vitamin
%p
  %b Bitamin:
  = @food.bitamin
%p
  %b Calcium:
  = @food.Calcium
%p
  %b Iron:
  = @food.iron

= link_to 'Edit', edit_food_path(@food)
\|
= link_to 'Back', foods_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> ConCal | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/Proposal.html.erb
<% provide(:title, "Proposal") %>
<!DOCTYPE html>
<html>
<head>
  <title>
    Proposal
  </title>
    <style>
@font face {
    font family = 'CSChatThai';
    src = url('/Concal/app/views/static_pages/CSChatThaiUI.ttf');
    font weight = normal;
    font style = normal;
}
</style>
</head>
<body>
<font face = 'CSChatThai'>
<h2>ชื่อโครงงาน Concal</h2>
<h3>ปัญหาและวัตถุประสงค์</h3>
<p><dd>เนื่องจากปัจจุบันได้มีการหันมาสนใจในด้านการรักษาสุขภาพมากขึ้น ทางเราจึงได้คิดแอพลิแคชั่นที่ใช้ในการคำนวน แคลอรี่ในแต่ละมื้อ และบันทึกมื้ออาหารที่รับประทานเข้าไป นอกจากนี้ยังเทรนเนอร์ที่สามารถช่วยให้คำแนะนำในแต่ละวันอีกด้วย</dd></p>
<h3>กลุ่มเป้าหมายผู้ใช้งาน</h3>
<p><dd>ทุกช่วงอายุที่ต้องการคำนวนแคลอรี่ที่ใช้ในแต่ละวัน และเทรนเนอร์ผู้ฝึกสอน</dd></p>
<h3>รายละเอียดของระบบ</h3>
<p><dd>-ทางด้านผู้ใช้สามารถค้นหาแคลอรี่ของอาหารได้<br>
-ทางด้านผู้ใช้สามารถคํานวณปริมาณแคลอรี่ได้<br>
-ทางด้านผู้ใช้สามารถปรึกษาพูดคุยกับเทรนเนอร์ได้<br>
-ทางด้านผู้ใช้สามารถรับรู้ข้อมูลปริมาณสารอาหาร 5 หมู่อาหารในแต่ละวัน<br>
-ทางด้านผู้ใช้ที่เป็นเทรนเนอร์สามารถให้คำปรึกษาแก่user<br>
-ทางด้านผู้ใช้ที่เป็นเทรนเนอร์สามารถจัดตารางอาหารให้แก่ user ได้</dd></p>

<h3>LoFi Ui</h3>

<%= image_tag "beforeSignup.jpg" %>
<%= image_tag "Signup.jpg" %>
<%= image_tag "Login.jpg" %>
<%= image_tag "Main.jpg" %>
<%= image_tag "AddAndcal.jpg" %>
<%= image_tag "Conclude.jpg" %>
<%= image_tag "Chat.jpg" %>
<%= image_tag "SelectTrianer.jpg" %>
<%= image_tag "TrainerAccept.jpg" %>
<%= image_tag "Editnormal.jpg" %>
<%= image_tag "Edittrainer.jpg" %>


</font>
</body>
</html>

app/views/static_pages/User.html.erb
<% provide(:title, "User Story") %>
<table border = 1 align=center>
  <th>User Story</th>
  
  <tr><td>As a customer.<br>
I want to receive the age, height, and weight of users.<br>
So that, the application can calculate the calories that they need per day.</td></tr>
<tr><td>As a customer.<br>
I want to know the calories of users that they need per day.<br>
So that, the application can tell what food that they can eat.</td></tr>
<tr><td>As a customer.<br>
I want to know what type of food that they usually choose to eat.<br>
So that, the application can find and tell the food that be similar to their favorite.</td></tr>
<tr><td>As a user.<br>
I want to choose that I will register as a trainer or normal member.</td></tr>
<tr><td>As a user.<br>
I want to have a mail box.<br>
So that, I can communicate with others.</td></tr>
<tr><td>As a normal member.<br>
I want to check trainers’ name list.<br>
So that, I can consider who I’ll request for coaching.</td></tr>
<tr><td>As a trainer.<br>
I want to access the information of a normal member.<br>
So that, I can coach him/her.</td></tr>
</table>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h2>Members</h2>
<p>1.นาย สุขสันต์ แท่นทรายทอง 6010613542
<br>2.นาย ธนัท เจียรสุวรรณ 6010613575
<br>3.นาย รธีพัฒน์ พระจันทร์ทอง 60010613393
<br>4.นาย ปฏิภาณ ไชยวิสุทธิกุล 6010613609
</p>
<h2>Project Proposal</h2>
<a href="static_pages/Proposal">Link to Proposal</a>
<h2>User Story</h2>
<a href="static_pages/User">Link to user story</a>
<h2>Link to Git</h2>
<a href="https://gitlab.com/6010613575/concal.git">Gitlab</a>
<h2>Link to pivotal tracker</h2>
<a href="https://www.pivotaltracker.com/n/projects/2406033">Pivotal tracker</a>

<h2>BDD</h2>
<a href="foods">Link to BDD</a>